// bpAnalysisMock.ts

export type BpDocumentAiFields = {
  absence_maladie_montant: number[];
  avantage_nature_montant: number[];
  convention_collective: string | null;
  date_anciennete: Date | null;
  date_entree_entreprise: Date | null;
  debut_periode_emploi: Date | null;
  fin_periode_emploi: Date | null;
  heure_supplementaires_montant: number[];
  mois_bulletin_de_paie: string | null;
  nom_salarie: string | null;
  periode_arret_maladie: string[];
  primes_montant: number[];
  salaire_base: number | null;
  salaire_brut_mensuel: number | null;
  sous_total_salaire_base_montant: number | null;
  absence_non_justifie_montant: number[];
  absence_non_justifie_periode: string[];
  conge_paye_montant: number[];
  conge_paye_periode: string[];
  conge_sans_solde_montant: number[];
  conge_sans_solde_nombre: number[];
  nombre_conge_paye: number[];
  heures_travail: number[];
  majoration_heures_montant: number[];
};

export type BpAnalysis = BpDocumentAiFields & {
  sickLeaveWorkingDays: number;
  unjustifiedAbsenceWorkingDays: number;
};

export const bpAnalysisMock: BpAnalysis[] = [
  // January
  {
    absence_maladie_montant: [],
    avantage_nature_montant: [50],
    convention_collective: null,
    date_anciennete: new Date("2019-01-15"),
    date_entree_entreprise: new Date("2018-12-01"),
    debut_periode_emploi: new Date("2023-01-01"),
    fin_periode_emploi: new Date("2023-01-31"),
    heure_supplementaires_montant: [20],
    mois_bulletin_de_paie: "Janvier",
    nom_salarie: "John Doe",
    periode_arret_maladie: [],
    primes_montant: [200],
    salaire_base: 3000,
    salaire_brut_mensuel: 3500,
    sous_total_salaire_base_montant: 3000,
    absence_non_justifie_montant: [],
    absence_non_justifie_periode: [],
    conge_paye_montant: [150],
    conge_paye_periode: ["2023-01-20"],
    conge_sans_solde_montant: [],
    conge_sans_solde_nombre: [],
    nombre_conge_paye: [2],
    heures_travail: [160],
    majoration_heures_montant: [75],
    sickLeaveWorkingDays: 1,
    unjustifiedAbsenceWorkingDays: 0,
  },
  // February
  {
    absence_maladie_montant: [],
    avantage_nature_montant: [60],
    convention_collective: null,
    date_anciennete: new Date("2019-01-15"),
    date_entree_entreprise: new Date("2018-12-01"),
    debut_periode_emploi: new Date("2023-02-01"),
    fin_periode_emploi: new Date("2023-02-28"),
    heure_supplementaires_montant: [15],
    mois_bulletin_de_paie: "Février",
    nom_salarie: "Jane Doe",
    periode_arret_maladie: [],
    primes_montant: [210],
    salaire_base: 3100,
    salaire_brut_mensuel: 3600,
    sous_total_salaire_base_montant: 3100,
    absence_non_justifie_montant: [],
    absence_non_justifie_periode: [],
    conge_paye_montant: [140],
    conge_paye_periode: ["2023-02-20"],
    conge_sans_solde_montant: [],
    conge_sans_solde_nombre: [],
    nombre_conge_paye: [1],
    heures_travail: [158],
    majoration_heures_montant: [70],
    sickLeaveWorkingDays: 2,
    unjustifiedAbsenceWorkingDays: 1,
  },
  // March
  {
    absence_maladie_montant: [],
    avantage_nature_montant: [70],
    convention_collective: null,
    date_anciennete: new Date("2018-06-10"),
    date_entree_entreprise: new Date("2018-07-01"),
    debut_periode_emploi: new Date("2023-03-01"),
    fin_periode_emploi: new Date("2023-03-31"),
    heure_supplementaires_montant: [25],
    mois_bulletin_de_paie: "Mars",
    nom_salarie: "Alice Smith",
    periode_arret_maladie: [],
    primes_montant: [220],
    salaire_base: 3200,
    salaire_brut_mensuel: 3700,
    sous_total_salaire_base_montant: 3200,
    absence_non_justifie_montant: [],
    absence_non_justifie_periode: [],
    conge_paye_montant: [130],
    conge_paye_periode: ["2023-03-25"],
    conge_sans_solde_montant: [],
    conge_sans_solde_nombre: [],
    nombre_conge_paye: [2],
    heures_travail: [162],
    majoration_heures_montant: [80],
    sickLeaveWorkingDays: 0,
    unjustifiedAbsenceWorkingDays: 0,
  },
  // April
  {
    absence_maladie_montant: [],
    avantage_nature_montant: [55],
    convention_collective: null,
    date_anciennete: new Date("2017-08-15"),
    date_entree_entreprise: new Date("2017-09-01"),
    debut_periode_emploi: new Date("2023-04-01"),
    fin_periode_emploi: new Date("2023-04-30"),
    heure_supplementaires_montant: [30],
    mois_bulletin_de_paie: "Avril",
    nom_salarie: "Bob Brown",
    periode_arret_maladie: [],
    primes_montant: [230],
    salaire_base: 3300,
    salaire_brut_mensuel: 3800,
    sous_total_salaire_base_montant: 3300,
    absence_non_justifie_montant: [],
    absence_non_justifie_periode: [],
    conge_paye_montant: [160],
    conge_paye_periode: ["2023-04-20"],
    conge_sans_solde_montant: [],
    conge_sans_solde_nombre: [],
    nombre_conge_paye: [1],
    heures_travail: [165],
    majoration_heures_montant: [85],
    sickLeaveWorkingDays: 1,
    unjustifiedAbsenceWorkingDays: 0,
  },
  // May
  {
    absence_maladie_montant: [],
    avantage_nature_montant: [65],
    convention_collective: null,
    date_anciennete: new Date("2016-03-20"),
    date_entree_entreprise: new Date("2016-04-01"),
    debut_periode_emploi: new Date("2023-05-01"),
    fin_periode_emploi: new Date("2023-05-31"),
    heure_supplementaires_montant: [18],
    mois_bulletin_de_paie: "Mai",
    nom_salarie: "Charlie Black",
    periode_arret_maladie: [],
    primes_montant: [240],
    salaire_base: 3400,
    salaire_brut_mensuel: 3900,
    sous_total_salaire_base_montant: 3400,
    absence_non_justifie_montant: [],
    absence_non_justifie_periode: [],
    conge_paye_montant: [170],
    conge_paye_periode: ["2023-05-22"],
    conge_sans_solde_montant: [],
    conge_sans_solde_nombre: [],
    nombre_conge_paye: [1],
    heures_travail: [170],
    majoration_heures_montant: [90],
    sickLeaveWorkingDays: 2,
    unjustifiedAbsenceWorkingDays: 0,
  },
  // June
  {
    absence_maladie_montant: [],
    avantage_nature_montant: [75],
    convention_collective: null,
    date_anciennete: new Date("2016-03-20"),
    date_entree_entreprise: new Date("2016-04-01"),
    debut_periode_emploi: new Date("2023-06-01"),
    fin_periode_emploi: new Date("2023-06-30"),
    heure_supplementaires_montant: [22],
    mois_bulletin_de_paie: "Juin",
    nom_salarie: "Diane White",
    periode_arret_maladie: [],
    primes_montant: [250],
    salaire_base: 3500,
    salaire_brut_mensuel: 4000,
    sous_total_salaire_base_montant: 3500,
    absence_non_justifie_montant: [],
    absence_non_justifie_periode: [],
    conge_paye_montant: [180],
    conge_paye_periode: ["2023-06-25"],
    conge_sans_solde_montant: [],
    conge_sans_solde_nombre: [],
    nombre_conge_paye: [2],
    heures_travail: [168],
    majoration_heures_montant: [95],
    sickLeaveWorkingDays: 1,
    unjustifiedAbsenceWorkingDays: 1,
  },
  // July
  {
    absence_maladie_montant: [],
    avantage_nature_montant: [80],
    convention_collective: null,
    date_anciennete: new Date("2015-11-10"),
    date_entree_entreprise: new Date("2015-12-01"),
    debut_periode_emploi: new Date("2023-07-01"),
    fin_periode_emploi: new Date("2023-07-31"),
    heure_supplementaires_montant: [28],
    mois_bulletin_de_paie: "Juillet",
    nom_salarie: "Eve Green",
    periode_arret_maladie: [],
    primes_montant: [260],
    salaire_base: 3600,
    salaire_brut_mensuel: 4100,
    sous_total_salaire_base_montant: 3600,
    absence_non_justifie_montant: [],
    absence_non_justifie_periode: [],
    conge_paye_montant: [190],
    conge_paye_periode: ["2023-07-20"],
    conge_sans_solde_montant: [],
    conge_sans_solde_nombre: [],
    nombre_conge_paye: [1],
    heures_travail: [172],
    majoration_heures_montant: [100],
    sickLeaveWorkingDays: 0,
    unjustifiedAbsenceWorkingDays: 0,
  },
  // August
  {
    absence_maladie_montant: [],
    avantage_nature_montant: [85],
    convention_collective: null,
    date_anciennete: new Date("2015-11-10"),
    date_entree_entreprise: new Date("2015-12-01"),
    debut_periode_emploi: new Date("2023-08-01"),
    fin_periode_emploi: new Date("2023-08-31"),
    heure_supplementaires_montant: [35],
    mois_bulletin_de_paie: "Août",
    nom_salarie: "Frank Blue",
    periode_arret_maladie: [],
    primes_montant: [270],
    salaire_base: 3700,
    salaire_brut_mensuel: 4200,
    sous_total_salaire_base_montant: 3700,
    absence_non_justifie_montant: [],
    absence_non_justifie_periode: [],
    conge_paye_montant: [200],
    conge_paye_periode: ["2023-08-22"],
    conge_sans_solde_montant: [],
    conge_sans_solde_nombre: [],
    nombre_conge_paye: [1],
    heures_travail: [175],
    majoration_heures_montant: [105],
    sickLeaveWorkingDays: 2,
    unjustifiedAbsenceWorkingDays: 0,
  },
  // September
  {
    absence_maladie_montant: [],
    avantage_nature_montant: [90],
    convention_collective: null,
    date_anciennete: new Date("2014-09-10"),
    date_entree_entreprise: new Date("2014-10-01"),
    debut_periode_emploi: new Date("2023-09-01"),
    fin_periode_emploi: new Date("2023-09-30"),
    heure_supplementaires_montant: [32],
    mois_bulletin_de_paie: "Septembre",
    nom_salarie: "Grace Yellow",
    periode_arret_maladie: [],
    primes_montant: [280],
    salaire_base: 3800,
    salaire_brut_mensuel: 4300,
    sous_total_salaire_base_montant: 3800,
    absence_non_justifie_montant: [],
    absence_non_justifie_periode: [],
    conge_paye_montant: [210],
    conge_paye_periode: ["2023-09-20"],
    conge_sans_solde_montant: [],
    conge_sans_solde_nombre: [],
    nombre_conge_paye: [2],
    heures_travail: [178],
    majoration_heures_montant: [110],
    sickLeaveWorkingDays: 1,
    unjustifiedAbsenceWorkingDays: 1,
  },
  // October
  {
    absence_maladie_montant: [],
    avantage_nature_montant: [95],
    convention_collective: null,
    date_anciennete: new Date("2014-09-10"),
    date_entree_entreprise: new Date("2014-10-01"),
    debut_periode_emploi: new Date("2023-10-01"),
    fin_periode_emploi: new Date("2023-10-31"),
    heure_supplementaires_montant: [40],
    mois_bulletin_de_paie: "Octobre",
    nom_salarie: "Henry Violet",
    periode_arret_maladie: [],
    primes_montant: [290],
    salaire_base: 3900,
    salaire_brut_mensuel: 4400,
    sous_total_salaire_base_montant: 3900,
    absence_non_justifie_montant: [],
    absence_non_justifie_periode: [],
    conge_paye_montant: [220],
    conge_paye_periode: ["2023-10-20"],
    conge_sans_solde_montant: [],
    conge_sans_solde_nombre: [],
    nombre_conge_paye: [1],
    heures_travail: [180],
    majoration_heures_montant: [115],
    sickLeaveWorkingDays: 2,
    unjustifiedAbsenceWorkingDays: 0,
  },
  // November
  {
    absence_maladie_montant: [],
    avantage_nature_montant: [100],
    convention_collective: null,
    date_anciennete: new Date("2013-05-05"),
    date_entree_entreprise: new Date("2013-06-01"),
    debut_periode_emploi: new Date("2023-11-01"),
    fin_periode_emploi: new Date("2023-11-30"),
    heure_supplementaires_montant: [45],
    mois_bulletin_de_paie: "Novembre",
    nom_salarie: "Ivy Orange",
    periode_arret_maladie: [],
    primes_montant: [300],
    salaire_base: 4000,
    salaire_brut_mensuel: 4500,
    sous_total_salaire_base_montant: 4000,
    absence_non_justifie_montant: [],
    absence_non_justifie_periode: [],
    conge_paye_montant: [230],
    conge_paye_periode: ["2023-11-25"],
    conge_sans_solde_montant: [],
    conge_sans_solde_nombre: [],
    nombre_conge_paye: [2],
    heures_travail: [182],
    majoration_heures_montant: [120],
    sickLeaveWorkingDays: 1,
    unjustifiedAbsenceWorkingDays: 1,
  },
  // December
  {
    absence_maladie_montant: [],
    avantage_nature_montant: [110],
    convention_collective: "Restauration rapide",
    date_anciennete: new Date("2013-05-05"),
    date_entree_entreprise: new Date("2013-06-01"),
    debut_periode_emploi: new Date("2023-12-01"),
    fin_periode_emploi: new Date("2023-12-31"),
    heure_supplementaires_montant: [50],
    mois_bulletin_de_paie: "Décembre",
    nom_salarie: "Jack Purple",
    periode_arret_maladie: [],
    primes_montant: [310],
    salaire_base: 4100,
    salaire_brut_mensuel: 4600,
    sous_total_salaire_base_montant: 4100,
    absence_non_justifie_montant: [],
    absence_non_justifie_periode: [],
    conge_paye_montant: [240],
    conge_paye_periode: ["2023-12-20"],
    conge_sans_solde_montant: [],
    conge_sans_solde_nombre: [],
    nombre_conge_paye: [1],
    heures_travail: [185],
    majoration_heures_montant: [125],
    sickLeaveWorkingDays: 2,
    unjustifiedAbsenceWorkingDays: 0,
  },
];

export default bpAnalysisMock;
